# Generated by Django 3.1.2 on 2021-02-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='caption',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='meme',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
